eternum_words = [
	'Orion Richards',
	'Praetorian',
	'Calypso',
	'Dalia Carter',
	'Penelope Carter',
	'Nancy Carter',
	'Nova Johnson',
	'Luna Hernandez',
	'Alexandra',
	'Axel Bardot',
	'William Bardot',
	'Annie Winters',
	'Ulysses',
	'The Founder',
	'Neural Implant',
	'Eternum',
	'Red Herring',
	'The New World',
	'Ion',
	'Kredon',
	'Micaela Garcia',
	'Doors of Acheron',
	'Idriel',
	'Nhurein',
	'Mr Keating',
	'Sir Jermaine of Noriander',
	'Cassian',
	'Aysha',
	'Raul and Noah',
	'Chop Chop',
	'Hyas',
	'Dione',
	'Gems of Doom',
	'Amulet of Blair',
	'Ekabar',
	'Thanatos',
	'Sandra Johnson',
	'Rory Johnson',
	'Maurice',
	'Enzo',
	'The Syndicate',
	'Alicia Flink',
	'Kai',
	'Millie',
	'Gertrude',
	'Priscilla Bardot',
	'Philippe',
	'Valentino',
	'Ogygia',
	'Agora',
	'The Immortals',
	'Dimeritium',
	'Peredhil',
	'Eldari',
	'Valley of the Kings',
	'Maat',
	'Avery',
	'Snuggles',
	'Brownies or Bagels',
	'Semper Invicta',
	'Andromeda',
	'Warthogs',
	'Balbus Bundledore',
	'Boyle Mansion',
	'Rockefeller',
	'Cornelius Garrington',
	'Wenlin',
	'Professor Owler',
	'Reminiscecombobulator',
	'Professor Mandrake',
	'Veritaserum',
	'Syrup of Arnica',
	'Professor Abbot',
	'Boggles',
	'Increarbus Severum',
	'Maximus',
	'Western Roman Empire',
	'Rotunda',
	'Jasticus',
	'New Vegas',
	'Bennie Garrington',
	'Hydroxynosinemate',
	'Brock',
	'The Cove',
	'Stormblade',
	'AstroCorp',
	'Take the leap of faith',
	'Katniss',
	'Vasil',
	'Commander Hasler',
	'Doctor Mercer',
	'Doctor Du Pont',
	'Lisa Astor',
	'Mr. Mos',
	'Delilah Warren',
	'Pancho',
	'Hugo Hernandez',
	'Victor Hernandez',
	'Olivia Hernandez',
	'Regina',
	'Akira-san',
	'Haskel',
	'Dolores',
	'Professor Connor',
	'Clarence',
	'Wyatt Pittman',
	'Wagner',
	'Harley Jones',
	'Clonk',
	'Gideon Cook',
	'Anna Piaget',
	'Gemini',
	'Sister Baek',
	'Dopplemorpher',
	'Boone',
	'Roach',
	'Frontier Trails',
	'El Coyote',
	'Anima',
	'Lily',
	'Marco',
	'One Piece',
	'Pochita',
	'Hollowbrook',
	'Father Bakhar',
	'Lazarus Iliescu',
	'Mortimer',
	'Lysa Iliescu',
	'Tissle',
	'Duke and Burpee',
	'Fangred',
	'Aspen',
	'Lamborghini',
	'Tortuga',
	'Zigzagopopolis',
	'Igor'
]