vidya_words = [
	"The Legend of Zelda: Breath of the Wild",
	"Super Mario Bros",
	"Minecraft",
	"The Witcher 3: Wild Hunt",
	"Tetris",
	"Grand Theft Auto V",
	"Red Dead Redemption 2",
	"The Elder Scrolls V: Skyrim",
	"Half-Life 2",
	"The Last of Us",
	"Super Mario 64",
	"Dark Souls",
	"Super Smash Bros. Ultimate",
	"Pokémon Red/Blue/Green",
	"Fortnite",
	"World of Warcraft",
	"Portal 2",
	"Halo: Combat Evolved",
	"Street Fighter II",
	"Chrono Trigger",
	"BioShock",
	"Metal Gear Solid",
	"Final Fantasy VII",
	"Doom",
	"Call of Duty: Modern Warfare",
	"The Legend of Zelda: Ocarina of Time",
	"Resident Evil 4",
	"Super Mario Odyssey",
	"Hades",
	"Pac-Man",
	"Celeste",
	"Bloodborne",
	"Fallout: New Vegas",
	"God of War",
	"Stardew Valley",
	"Undertale",
	"League of Legends",
	"Overwatch",
	"Animal Crossing: New Horizons",
	"Journey",
	"The Sims",
	"Silent Hill 2",
	"Persona",
	"Shadow of the Colossus",
	"Sid Meier's Civilization VI",
	"Hollow Knight",
	"Mega Man 2",
	"Diablo II",
	"Donkey Kong Country",
	"Counter-Strike: Global Offensive",
	"StarCraft",
	"Terraria",
	"Super Metroid",
	"Rocket League",
	"Sekiro: Shadows Die Twice",
	"XCOM 2",
	"Cuphead",
	"Dota 2",
	"Monster Hunter: World",
	"Kingdom Hearts",
	"Assassin's Creed II",
	"Celeste",
	"Horizon Zero Dawn",
	"Metroid Prime",
	"Dishonored 2",
	"Super Mario Galaxy",
	"Batman: Arkham City",
	"The Legend of Zelda: A Link to the Past",
	"The Binding of Isaac",
	"Baldur's Gate II: Shadows of Amn",
	"Star Wars: Knights of the Old Republic",
	"Dragon Age: Origins",
	"Deus Ex",
	"Control",
	"Ghost of Tsushima",
	"Halo 3",
	"Fire Emblem: Three Houses",
	"Castlevania: Symphony of the Night",
	"Apex Legends",
	"Splatoon",
	"NieR: Automata",
	"Super Mario Galaxy 2",
	"Journey",
	"Divinity: Original Sin 2",
	"The Legend of Zelda: Wind Waker",
	"Super Mario World",
	"Forza Horizon 4",
	"The Outer Worlds",
	"Darkest Dungeon",
	"Super Meat Boy",
	"Hollow Knight",
	"Tony Hawk's Pro Skater 2",
	"Return of the Obra Dinn",
	"Sekiro: Shadows Die Twice",
	"Dead Cells",
	"Luigi's Mansion 3",
	"Thief II: The Metal Age",
	"Firewatch",
	"Subnautica",
	"Ori and the Blind Forest",
	"Dead Space",
	"Team Fortress 2",
	"Titanfall 2",
	"Horizon Zero Dawn",
	"The Stanley Parable",
	"Animal Crossing: Wild World",
	"Mario Kart 8 Deluxe",
	"Hades",
	"Age of Empires II",
	"System Shock 2",
	"Bioshock Infinite",
	"Grand Theft Auto: San Andreas",
	"Papers, Please",
	"Xenoblade Chronicles",
	"Borderlands 2",
	"Skate 3",
	"The Elder Scrolls III: Morrowind",
	"Assassin's Creed IV: Black Flag",
	"Phoenix Wright: Ace Attorney",
	"Yakuza 0",
	"Slay the Spire",
	"Control",
	"Outer Wilds",
	"Sekiro: Shadows Die Twice",
	"Bayonetta 2",
	"The Witness",
	"Bloodborne",
	"Celeste",
	"Monster Hunter Rise",
	"Marvel's Spider-Man",
	"Dishonored",
	"The Legend of Zelda: Majora's Mask",
	"Rise of the Tomb Raider",
	"Devil May Cry 5",
	"NieR Automata",
	"The Legend of Zelda: Link's Awakening",
	"Dragon Quest XI",
	"Super Smash Bros Melee",
	"Control",
	"Katamari Damacy",
	"Ratchet & Clank: Rift Apart",
	"Hollow Knight: Silksong",
	"Shovel Knight",
	"Metroid Dread",
	"Ori and the Will of the Wisps",
	"The Talos Principle",
	"Hyper Light Drifter",
	"Uncharted 4: A Thief's End",
	"Sonic the Hedgehog 2",
	"Horizon Forbidden West",
	"Marvel's Spider-Man: Miles Morales",
	"Returnal",
	"Genshin Impact",
	"The Last of Us Part II",
	"Demon's Souls",
	"Mass Effect",
	"Inside",
	"LittleBigPlanet",
	"Risk of Rain 2",
	"Cuphead: The Delicious Last Course",
	"Horizon Zero Dawn",
	"Ratchet & Clank",
	"Hitman 3",
	"Fire Emblem: Awakening",
	"Hollow Knight",
	"Ghost Trick: Phantom Detective",
	"Hades",
	"Celeste",
	"Death Stranding",
	"Hades",
	"Metroid Fusion",
	"Okami",
	"BioShock",
	"Disco Elysium",
	"Hollow Knight",
	"Kentucky Route Zero",
	"The Witcher 2: Assassins of Kings",
	"Sekiro: Shadows Die Twice",
	"Hades",
	"Monster Hunter Stories 2: Wings of Ruin",
	"Ghost of Tsushima",
	"Cyberpunk 2077",
	"Hades",
	"The Legend of Zelda: Skyward Sword HD",
	"Metroid Prime 4"
]